language: node_js
node_js:
- "stable"
- "8"
- "10"
- "12"

cache: npm
before_install:
- npm install -g greenkeeper-lockfile
before_script:
- npm run setup
- ./build.sh
script:
- npm run build
- echo "Success!"
after_script: greenkeeper-lockfile-upload